// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_AlphaVantageProvider.cpp"
#include "UVLADIE3JM/moc_FinnhubProvider.cpp"
#include "UVLADIE3JM/moc_MainWindow.cpp"
#include "UVLADIE3JM/moc_PolygonProvider.cpp"
#include "UVLADIE3JM/moc_SettingsDialog.cpp"
#include "UVLADIE3JM/moc_StockDataProvider.cpp"
#include "UVLADIE3JM/moc_TwelveDataProvider.cpp"
